FROM node:16

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

# Install serve globally
RUN npm install -g serve

# Use serve to serve the build folder
CMD ["serve", "-s", "build", "-l", "3000"]
