
services:
  frontend:
    build: ./my_app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./my_app/Backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://Bilalkhan:Pakistan@cluster1.moct8fi.mongodb.net/Mlops
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"

  auth:
    build: ./my_app/backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://Bilalkhan:Pakistan@cluster1.moct8fi.mongodb.net/Wasay_MLOPS_Task6
      - JWT_SECRET=fuifnfiuebg5454$%^&*(*&^%bjdbibiuf%^&*      